feat: add generate-site.sh
aurelia/aurelia.github.io-old pull request #13
Opened 2020-05-28 22:33 UTC by 3cp

Use local refresh shallow cloned documentation and blog repos. Use local refresh latest npm packages for API doc.

-----

The single bash script generate-site.sh does all the work.

This ensures only publishing API doc against latest npm packages, only publish doc and blog against relative repo master branch.

The API doc setup is good to keep.

But I am not sure about the documentation and blog repo, especially for blog. If they cause more trouble than help, let me roll them back.

2020-05-28 22:34 UTC, 3cp commented
I tested generated site, all work well. This PR did not commit those updated files.

2020-05-31 00:02 UTC, EisenbergEffect commented on package.json
> +    "aurelia-site-generator": "aurelia/site-generator",
What does this version designator do? Does it just get the latest master from GitHub?

2020-05-31 00:02 UTC, EisenbergEffect commented on generate-site.sh
> +npx au-site generate
Will this use the version of au-site that is specified in the package.json?

2020-05-31 00:18 UTC, 3cp commented on package.json
> +    "aurelia-site-generator": "aurelia/site-generator",
That's the syntax to target github repo master branch. The full form is `github:aurelia/site-generator#master`.

2020-05-31 00:19 UTC, 3cp commented on generate-site.sh
> +npx au-site generate
Npx will use locally installed package first, then fall back to globally installed, then fall back to remote download.

2020-05-31 00:27 UTC, 3cp commented on generate-site.sh
> +npx au-site generate
This works for local/global package even when bin name is different from package name. 
It doesn't work for remote download because npx will try npm package au-site.

2020-06-13 17:43 UTC, EisenbergEffect commented on generate-site.sh
> +npx au-site generate
What if I make a code change to the site-generator locally, and have that linked. Will it use my locally linked version? Or do I need to release the site generator to npm first before I can use it locally? Or just push to master?

Mainly, I'm just trying to understand what the workflow would be if I had to work on changes to both the site generator and the Aurelia site itself at the same time.

2020-06-13 21:21 UTC, 3cp commented on generate-site.sh
> +npx au-site generate
The setup is not flexible for that. To use your local change, you can

1. either push up your local change to remote master
2. or comment out the last `npx ...`, then manually run `au-site ...` (assuming you got local site-generator linked globally).

2020-06-13 23:39 UTC, 3cp commented on generate-site.sh
> +npx au-site generate
The version in package.json uses github site-generator repo, has no requirement on publishing to npm.

2020-06-14 01:04 UTC, EisenbergEffect commented on generate-site.sh
> +npx au-site generate
Makes sense. Thanks!

2020-06-14 01:10 UTC, EisenbergEffect requested changes

2020-06-14 01:10 UTC, EisenbergEffect commented on au-site.json
> +    "src": "./dep_repos/blog",
I'm not sure this change is going to work. The reason for that is that blog operations can alter the source files. For example, when a blog post is published, it gets removed from the drafts folder and then put into the published folder. The metadata gets encoded in the yaml header as part of that. It's then expected that it gets committed to the repo. If a blog is updated, it also updates the blog metadata.

I guess it will still work since you're checking out the blog...but it's strange for me because I've already got all this checked out on my machine and this sort of messes up my workflow for publishing blogs a bit.

The docs stuff isn't quite the same. That should be fine. I'm just a bit hesitant about this part.

2020-06-14 01:41 UTC, 3cp commented on au-site.json
> +    "src": "./dep_repos/blog",
That's why I asked. Let me revert the part for blog.

2020-06-14 01:59 UTC, 3cp commented
Blog setup has been restored.

2020-06-14 02:05 UTC, EisenbergEffect commented
Funny. I actually forgot about your original question. Thanks for making that change. I think the rest should be fine. I'll make one more quick review and then likely merge. Thanks for helping to improve this!

2020-06-14 02:06 UTC, EisenbergEffect approved these changes

2020-06-14 02:06 UTC, merged